const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";

export {
  FETCH_ALL_PRODUCTS,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  AUTHENTICATION,
  LOGOUT,
};
